spring:
  application:
    name: notification
  cloud:
    openfeign:
      httpclient:
        enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1q2w3e}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email, https://www.googleapis.com/auth/cloud-platform
            redirect-uri: "http://localhost:8100/login/oauth2/code/google"

  # ZIPKIN TRACING
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    zipkin:
      base-url: http://zipkin:9411

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}
  instance:
    preferIpAddress: false
    hostname: notification
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,traces

server:
  port: ${SERVER_PORT:8100}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    com.example.Notification: DEBUG
#server:
#  port: 8100
#
#spring:
#  application:
#    name: notification
#  cloud:
#    openfeign:
#      httpclient:
#        enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1q2w3e
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        '[default_schema]': public
#
#  # Configurare OAuth2 cu Google
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: openid, profile, email, https://www.googleapis.com/auth/cloud-platform
#            redirect-uri: "http://localhost:8100/login/oauth2/code/google"
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
#
#eureka:
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.application.name}:${server.port}
#    health-check-url-path: /actuator/health
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics
#  endpoint:
#    health:
#      show-details: always